import {
  describe, it, expect,
} from 'vitest';
import processData from '../src/data/processData';

describe('processData unit test', () => {
  it('returns processed data for both metric and imperial units', () => {
    const filteredData = {
      current: {
        description: 'few clouds',
        icon: '02n',
        temp: 298.85,
        feelsLike: 299.72,
        pop: 0.52,
        windSpeed: 1.54,
        windDeg: 260,
        humidity: 86,
        uvi: 0,
        visibility: 10000,
        clouds: 20,
        sunrise: 1685741165,
        sunset: 1685787716,
        country: null,
      },
      daily: [
        {
          dt: 1685761200,
          description: 'heavy intensity rain',
          icon: '10d',
          sunrise: 1685741165,
          sunset: 1685787716,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 303.91,
          tempNight: 300.13,
          feelsLikeDay: 309.55,
          feelsLikeNight: 303.13,
          humidity: 68,
          windSpeed: 4.81,
          windDeg: 248,
          clouds: 96,
          pop: 1,
          uvi: 12.24,
        },
        {
          dt: 1685847600,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1685827566,
          sunset: 1685874135,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 301.43,
          tempNight: 298.96,
          feelsLikeDay: 305.62,
          feelsLikeNight: 299.89,
          humidity: 78,
          windSpeed: 3.51,
          windDeg: 221,
          clouds: 100,
          pop: 1,
          uvi: 10.43,
        },
        {
          dt: 1685934000,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1685913967,
          sunset: 1685960553,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 300.7,
          tempNight: 300.26,
          feelsLikeDay: 303.9,
          feelsLikeNight: 303.34,
          humidity: 78,
          windSpeed: 3.32,
          windDeg: 143,
          clouds: 100,
          pop: 0.85,
          uvi: 7.29,
        },
        {
          dt: 1686020400,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1686000369,
          sunset: 1686046972,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 303.98,
          tempNight: 300.53,
          feelsLikeDay: 308.38,
          feelsLikeNight: 303.75,
          humidity: 63,
          windSpeed: 4.1,
          windDeg: 231,
          clouds: 92,
          pop: 1,
          uvi: 12.62,
        },
        {
          dt: 1686106800,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1686086771,
          sunset: 1686133390,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 303.88,
          tempNight: 300.56,
          feelsLikeDay: 308.67,
          feelsLikeNight: 304.31,
          humidity: 65,
          windSpeed: 2.82,
          windDeg: 236,
          clouds: 73,
          pop: 1,
          uvi: 12.77,
        },
        {
          dt: 1686193200,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1686173175,
          sunset: 1686219808,
          summary: 'There will be rain today',
          tempDay: 303.3,
          tempNight: 300.56,
          feelsLikeDay: 307.82,
          feelsLikeNight: 304.06,
          humidity: 67,
          windSpeed: 3.68,
          windDeg: 245,
          clouds: 96,
          pop: 1,
          uvi: 13,
        },
        {
          dt: 1686279600,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1686259579,
          sunset: 1686306226,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 303.8,
          tempNight: 300.54,
          feelsLikeDay: 308.74,
          feelsLikeNight: 304.01,
          humidity: 66,
          windSpeed: 5.28,
          windDeg: 262,
          clouds: 93,
          pop: 0.99,
          uvi: 13,
        },
        {
          dt: 1686366000,
          description: 'moderate rain',
          icon: '10d',
          sunrise: 1686345984,
          sunset: 1686392643,
          summary: 'Expect a day of partly cloudy with rain',
          tempDay: 303.54,
          tempNight: 300.34,
          feelsLikeDay: 308.38,
          feelsLikeNight: 303.53,
          humidity: 67,
          windSpeed: 6.8,
          windDeg: 261,
          clouds: 100,
          pop: 0.91,
          uvi: 13,
        },
      ],
    };

    expect(processData(filteredData)).toEqual({
      metric: {
        current: {
          description: 'Few Clouds',
          icon: '02n',
          temp: '26°C',
          feelsLike: '27°C',
          pop: '52%',
          windSpeed: '6 km/h',
          windDeg: 'W',
          humidity: '86%',
          uvi: '0 Low',
          visibility: '10 km',
          clouds: '20%',
          sunrise: '05:26 AM',
          sunset: '06:21 PM',
          country: null,
        },
        daily: [
          {
            dt: 'Today',
            description: 'Heavy Intensity Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:21 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '31°C',
            tempNight: '27°C',
            feelsLikeDay: '36°C',
            feelsLikeNight: '30°C',
            humidity: '68%',
            windSpeed: '17 km/h',
            windDeg: 'WSW',
            clouds: '96%',
            pop: '100%',
            uvi: '12 Extreme',
          },
          {
            dt: 'Tomorrow',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '28°C',
            tempNight: '26°C',
            feelsLikeDay: '32°C',
            feelsLikeNight: '27°C',
            humidity: '78%',
            windSpeed: '13 km/h',
            windDeg: 'SW',
            clouds: '100%',
            pop: '100%',
            uvi: '10 Very High',
          },
          {
            dt: 'Monday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '28°C',
            tempNight: '27°C',
            feelsLikeDay: '31°C',
            feelsLikeNight: '30°C',
            humidity: '78%',
            windSpeed: '12 km/h',
            windDeg: 'SE',
            clouds: '100%',
            pop: '85%',
            uvi: '7 High',
          },
          {
            dt: 'Tuesday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '31°C',
            tempNight: '27°C',
            feelsLikeDay: '35°C',
            feelsLikeNight: '31°C',
            humidity: '63%',
            windSpeed: '15 km/h',
            windDeg: 'SW',
            clouds: '92%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Wednesday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '31°C',
            tempNight: '27°C',
            feelsLikeDay: '36°C',
            feelsLikeNight: '31°C',
            humidity: '65%',
            windSpeed: '10 km/h',
            windDeg: 'SW',
            clouds: '73%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Thursday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'There will be rain today',
            tempDay: '30°C',
            tempNight: '27°C',
            feelsLikeDay: '35°C',
            feelsLikeNight: '31°C',
            humidity: '67%',
            windSpeed: '13 km/h',
            windDeg: 'WSW',
            clouds: '96%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Friday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '31°C',
            tempNight: '27°C',
            feelsLikeDay: '36°C',
            feelsLikeNight: '31°C',
            humidity: '66%',
            windSpeed: '19 km/h',
            windDeg: 'W',
            clouds: '93%',
            pop: '99%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Saturday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:24 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '30°C',
            tempNight: '27°C',
            feelsLikeDay: '35°C',
            feelsLikeNight: '30°C',
            humidity: '67%',
            windSpeed: '24 km/h',
            windDeg: 'W',
            clouds: '100%',
            pop: '91%',
            uvi: '13 Extreme',
          },
        ],

      },
      imperial: {
        current: {
          description: 'Few Clouds',
          icon: '02n',
          temp: '78°F',
          feelsLike: '78°F',
          pop: '52%',
          windSpeed: '3 mph',
          windDeg: 'W',
          humidity: '86%',
          uvi: '0 Low',
          visibility: '6 mi',
          clouds: '20%',
          sunrise: '05:26 AM',
          sunset: '06:21 PM',
          country: null,
        },
        daily: [
          {
            dt: 'Today',
            description: 'Heavy Intensity Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:21 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '87°F',
            tempNight: '81°F',
            feelsLikeDay: '98°F',
            feelsLikeNight: '86°F',
            humidity: '68%',
            windSpeed: '11 mph',
            windDeg: 'WSW',
            clouds: '96%',
            pop: '100%',
            uvi: '12 Extreme',
          },
          {
            dt: 'Tomorrow',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '83°F',
            tempNight: '78°F',
            feelsLikeDay: '90°F',
            feelsLikeNight: '80°F',
            humidity: '78%',
            windSpeed: '8 mph',
            windDeg: 'SW',
            clouds: '100%',
            pop: '100%',
            uvi: '10 Very High',
          },
          {
            dt: 'Monday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '82°F',
            tempNight: '81°F',
            feelsLikeDay: '87°F',
            feelsLikeNight: '86°F',
            humidity: '78%',
            windSpeed: '7 mph',
            windDeg: 'SE',
            clouds: '100%',
            pop: '85%',
            uvi: '7 High',
          },
          {
            dt: 'Tuesday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:22 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '87°F',
            tempNight: '81°F',
            feelsLikeDay: '95°F',
            feelsLikeNight: '87°F',
            humidity: '63%',
            windSpeed: '9 mph',
            windDeg: 'SW',
            clouds: '92%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Wednesday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '87°F',
            tempNight: '81°F',
            feelsLikeDay: '96°F',
            feelsLikeNight: '88°F',
            humidity: '65%',
            windSpeed: '6 mph',
            windDeg: 'SW',
            clouds: '73%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Thursday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'There will be rain today',
            tempDay: '86°F',
            tempNight: '81°F',
            feelsLikeDay: '94°F',
            feelsLikeNight: '88°F',
            humidity: '67%',
            windSpeed: '8 mph',
            windDeg: 'WSW',
            clouds: '96%',
            pop: '100%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Friday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:23 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '87°F',
            tempNight: '81°F',
            feelsLikeDay: '96°F',
            feelsLikeNight: '88°F',
            humidity: '66%',
            windSpeed: '12 mph',
            windDeg: 'W',
            clouds: '93%',
            pop: '99%',
            uvi: '13 Extreme',
          },
          {
            dt: 'Saturday',
            description: 'Moderate Rain',
            icon: '10d',
            sunrise: '05:26 AM',
            sunset: '06:24 PM',
            summary: 'Expect a day of partly cloudy with rain',
            tempDay: '87°F',
            tempNight: '81°F',
            feelsLikeDay: '95°F',
            feelsLikeNight: '87°F',
            humidity: '67%',
            windSpeed: '15 mph',
            windDeg: 'W',
            clouds: '100%',
            pop: '91%',
            uvi: '13 Extreme',
          },
        ],

      },
    });
  });
});
